/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SearchImagesRouteImport } from './routes/search/images'
import { Route as SearchNewsRouteImport } from './routes/search/news'
import { Route as SearchVideosRouteImport } from './routes/search/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const SearchImagesRoute = SearchImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => SearchRoute,
} as any)
const SearchNewsRoute = SearchNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SearchRoute,
} as any)
const SearchVideosRoute = SearchVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => SearchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRouteWithChildren
  '/search/images': typeof SearchImagesRoute
  '/search/news': typeof SearchNewsRoute
  '/search/videos': typeof SearchVideosRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search/images': typeof SearchImagesRoute
  '/search/news': typeof SearchNewsRoute
  '/search/videos': typeof SearchVideosRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRouteWithChildren
  '/search/images': typeof SearchImagesRoute
  '/search/news': typeof SearchNewsRoute
  '/search/videos': typeof SearchVideosRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/search/images'
    | '/search/news'
    | '/search/videos'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search/images' | '/search/news' | '/search/videos' | '/search'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/search/images'
    | '/search/news'
    | '/search/videos'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/images': {
      id: '/search/images'
      path: '/images'
      fullPath: '/search/images'
      preLoaderRoute: typeof SearchImagesRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/news': {
      id: '/search/news'
      path: '/news'
      fullPath: '/search/news'
      preLoaderRoute: typeof SearchNewsRouteImport
      parentRoute: typeof SearchRoute
    }
    '/search/videos': {
      id: '/search/videos'
      path: '/videos'
      fullPath: '/search/videos'
      preLoaderRoute: typeof SearchVideosRouteImport
      parentRoute: typeof SearchRoute
    }
  }
}

interface SearchRouteChildren {
  SearchImagesRoute: typeof SearchImagesRoute
  SearchNewsRoute: typeof SearchNewsRoute
  SearchVideosRoute: typeof SearchVideosRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchImagesRoute: SearchImagesRoute,
  SearchNewsRoute: SearchNewsRoute,
  SearchVideosRoute: SearchVideosRoute,
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
